# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../resources/qt_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AudioVisualizer(object):
    def setupUi(self, AudioVisualizer):
        AudioVisualizer.setObjectName("AudioVisualizer")
        AudioVisualizer.resize(1000, 700)
        AudioVisualizer.setStyleSheet("background-color: #283747")
        self.centralwidget = QtWidgets.QWidget(AudioVisualizer)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sound_lvl = QtWidgets.QProgressBar(self.centralwidget)
        self.sound_lvl.setMaximum(1000)
        self.sound_lvl.setProperty("value", 150)
        self.sound_lvl.setTextVisible(False)
        self.sound_lvl.setOrientation(QtCore.Qt.Vertical)
        self.sound_lvl.setObjectName("sound_lvl")
        self.horizontalLayout.addWidget(self.sound_lvl)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_fft = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_fft.setFont(font)
        self.label_fft.setStyleSheet("color: #FFFFFF")
        self.label_fft.setObjectName("label_fft")
        self.verticalLayout.addWidget(self.label_fft)
        self.fft_plot = PlotWidget(self.frame)
        self.fft_plot.setObjectName("fft_plot")
        self.verticalLayout.addWidget(self.fft_plot)
        self.pcm_normal = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pcm_normal.setFont(font)
        self.pcm_normal.setStyleSheet("color: #FFFFFF")
        self.pcm_normal.setObjectName("pcm_normal")
        self.verticalLayout.addWidget(self.pcm_normal)
        self.pcm_plot = PlotWidget(self.frame)
        self.pcm_plot.setObjectName("pcm_plot")
        self.verticalLayout.addWidget(self.pcm_plot)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #FFFFFF")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalSlider = QtWidgets.QSlider(self.frame)
        self.horizontalSlider.setMinimum(-25)
        self.horizontalSlider.setMaximum(25)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.horizontalLayout.addWidget(self.frame)
        AudioVisualizer.setCentralWidget(self.centralwidget)

        self.retranslateUi(AudioVisualizer)
        QtCore.QMetaObject.connectSlotsByName(AudioVisualizer)

    def retranslateUi(self, AudioVisualizer):
        _translate = QtCore.QCoreApplication.translate
        AudioVisualizer.setWindowTitle(_translate("AudioVisualizer", "AudioVisualizer"))
        self.label_fft.setText(_translate("AudioVisualizer", "Frequency data:"))
        self.pcm_normal.setText(_translate("AudioVisualizer", "Pulse-code modulation:"))
        self.label.setText(_translate("AudioVisualizer", "Phase manipulator:"))
from pyqtgraph import PlotWidget
